## Introducción

...

## Objetivo del analisis

...

## Preguntas

...

## Repositorio

...

## Librerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import plotly.express 
print("Librerias importadas correctamente")

Librerias importadas correctamente

## Importar datos

Link: https://www.kaggle.com/datasets/abisheksudarshan/customer-segmentation

In [2]:
df = pd.read_csv("./datos/train.csv")
print("Datos cargados correctamente")

Datos cargados correctamente

## EDA y ETL

info, describe, unicos, nulos, duplicados, categoricos, numericos,
eliminar, exportar csv final

In [3]:
df.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,462809,Male,No,22,No,Healthcare,1.0,Low,4.0,Cat_4,D
1,462643,Female,Yes,38,Yes,Engineer,NaN,Average,3.0,Cat_4,A
2,466315,Female,Yes,67,Yes,Engineer,1.0,Low,1.0,Cat_6,B
3,461735,Male,Yes,67,Yes,Lawyer,0.0,High,2.0,Cat_6,B
4,462669,Female,Yes,40,Yes,Entertainment,NaN,High,6.0,Cat_6,A

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               8068 non-null   int64
 1   Gender           8068 non-null   object
 2   Ever_Married     7928 non-null   object
 3   Age              8068 non-null   int64
 4   Graduated        7990 non-null   object
 5   Profession       7944 non-null   object
 6   Work_Experience  7239 non-null   float64
 7   Spending_Score   8068 non-null   object
 8   Family_Size      7733 non-null   float64
 9   Var_1            7992 non-null   object
 10  Segmentation     8068 non-null   object
dtypes: float64(2), int64(2), object(7)
memory usage: 693.5+ KB

* 8068 filas,
* 11 columnas,
* 3 tipos de datos. Float, Int y Object,
* Hay valores nulos o faltantes
* Hay 1 variables anonimizada (var_1)

In [6]:
df.describe()

                  ID          Age  Work_Experience  Family_Size
count    8068.000000  8068.000000      7239.000000  7733.000000
mean   463479.214551    43.466906         2.641663     2.850123
std      2595.381232    16.711696         3.406763     1.531413
min    458982.000000    18.000000         0.000000     1.000000
25%    461240.750000    30.000000         0.000000     2.000000
50%    463472.500000    40.000000         1.000000     3.000000
75%    465744.250000    53.000000         4.000000     4.000000
max    467974.000000    89.000000        14.000000     9.000000

## Graficos

...

## Conclusiones

...